#!/usr/bin/env bash
# script that configures an Ubuntu server with changing the ip addresses

cp /etc/hosts ~/hosts.new
echo "127.0.0.2     localhost" >> ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
