#!/usr/bin/env bash
# script that displays all active IPv4 IPs on the machine it’s executed on


ifconfig_output=$(ifconfig)
ipv4_addresses=$(echo "$ifconfig_output" | grep -oP 'inet\s+\K[\d.]+')
echo "$ipv4_addresses"
